// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtkloydwfemkcehpxcsc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0a2xveWR3ZmVta2NlaHB4Y3NjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MjYwNjksImV4cCI6MjA2NDUwMjA2OX0._cELW4jkpMGECF1DrSxrMcPu-QnZ4f54pf1jxIUHdm0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);